# Generated by Django 2.2.2 on 2019-06-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'created'), (1, 'accepted'), (2, 'finished'), (3, 'completed'), (-1, 'invalid'), (-2, 'canceled')], default=0)),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_tasks', to='angel.Angel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='angel.Angel')),
            ],
        ),
    ]
