# Generated by Django 2.2.2 on 2019-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='task',
            name='distribution',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
