# Generated by Django 2.2.2 on 2019-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190619_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='distribution',
            new_name='contribution',
        ),
    ]
