# Generated by Django 2.2.2 on 2019-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190619_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contribution',
            field=models.FloatField(default=0.0),
        ),
    ]
