# Generated by Django 2.2.1 on 2019-07-19 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190719_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 19, 5, 49, 43, 805073, tzinfo=utc), null=True),
        ),
    ]
