# Generated by Django 2.2.2 on 2019-06-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190620_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsnapshot',
            options={'ordering': ['-captured_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardsnapshot',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='info.Board'),
        ),
    ]
