# Generated by Django 2.2.2 on 2019-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190620_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsnapshot',
            name='captured_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
